package localai;

import burp.api.montoya.MontoyaApi;
import burp.api.montoya.http.message.HttpRequestResponse;
import burp.api.montoya.persistence.PersistedObject;
import com.google.gson.Gson;
import com.google.gson.JsonObject;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.text.html.HTMLEditorKit;
import java.awt.*;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.concurrent.CompletableFuture;

public class CopilotTab extends JPanel {
    // Core UI Components
    private final JEditorPane reportArea;      // Renders the HTML Report
    private final JTextArea requestPreviewArea; // Shows Sanitized Request

    // Chat Components
    private final JTextArea chatArea;          // Shows conversation history
    private final JTextField chatInput;        // User types here
    private final JButton sendChatButton;

    // Settings
    private final JTextField modelNameField;
    private final JTextField apiUrlField;

    // Data Context
    private HttpRequestResponse currentReqResp;
    private String fullContextString = "";     // The HTTP Request/Response
    private String currentReportText = "";     // The Analysis generated by AI
    private final StringBuilder chatHistory = new StringBuilder(); // Stores "User: ... AI: ..."

    // Services
    private final MontoyaApi api;
    private final PersistedObject persistence;
    private static final HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10))
            .build();
    private final Gson gson = new Gson();

    // Constants
    private static final String KEY_MODEL = "model_name";
    private static final String KEY_API_URL = "api_url";
    private static final String DEFAULT_MODEL = "dolphin-mistral";
    private static final String DEFAULT_API_URL = "http://localhost:11434/api/generate";

    // --- PROMPTS ---
    private static final String PROMPT_ANALYZE =
            "SYSTEM ROLE: You are a Senior Security Analyst.\n" +
                    "GOAL: Analyze the HTTP Request AND Response to identify logical risks.\n" +
                    "FORMAT: Output strictly valid HTML. Follow this EXACT structure:\n\n" +
                    "<h3>Summary</h3>\n" +
                    "<p>[One sentence on what the endpoint did]</p>\n" +
                    "<h3>Data Anatomy</h3>\n" +
                    "<ul>\n" +
                    "  <li><b>User Inputs:</b> [List parameters sent]</li>\n" +
                    "  <li><b>Server Tokens:</b> [List tokens found]</li>\n" +
                    "</ul>\n" +
                    "<h3>Response Findings</h3>\n" +
                    "<ul>\n" +
                    "  <li><b>Status:</b> [e.g. 200 OK, 403 Forbidden]</li>\n" +
                    "  <li><b>Reflected Input:</b> [Did any user input appear in the response? YES/NO + Details]</li>\n" +
                    "  <li><b>Sensitive Data:</b> [Any PII, keys, or stack traces in response?]</li>\n" +
                    "</ul>\n" +
                    "<h3>Risk Hypotheses</h3>\n" +
                    "<ul>\n" +
                    "  <li><b>[Risk Name]:</b> [Why it might exist based on the evidence]</li>\n" +
                    "</ul>\n\n" +
                    "CONSTRAINTS:\n" +
                    " - DO NOT generate attack payloads (no <script>).\n" +
                    " - Keep descriptions concise and professional.";

    private static final String PROMPT_REPORT =
            "SYSTEM ROLE: You are a Professional Penetration Tester writing a report.\n" +
                    "GOAL: Draft a vulnerability finding based on this traffic.\n" +
                    "CONSTRAINTS: Output valid HTML using <h3>, <p>, and <pre> tags.\n" +
                    "TASK:\n" +
                    "Draft a generic finding template for this type of vulnerability.\n" +
                    "Include sections: **Title**, **Description**, **Impact**, **Remediation**.";

    public CopilotTab(MontoyaApi api) {
        this.api = api;
        this.persistence = api.persistence().extensionData();
        
        setLayout(new BorderLayout());

        // --- 1. Top: Configuration ---
        JPanel settingsPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        settingsPanel.setBorder(new TitledBorder("Configuration"));
        
        settingsPanel.add(new JLabel("API URL:"));
        String savedUrl = persistence.getString(KEY_API_URL);
        apiUrlField = new JTextField(savedUrl != null ? savedUrl : DEFAULT_API_URL, 25);
        settingsPanel.add(apiUrlField);

        settingsPanel.add(new JLabel("Model:"));
        String savedModel = persistence.getString(KEY_MODEL);
        modelNameField = new JTextField(savedModel != null ? savedModel : DEFAULT_MODEL, 15);
        settingsPanel.add(modelNameField);
        
        JButton saveSettingsBtn = new JButton("Save");
        saveSettingsBtn.addActionListener(e -> saveSettings());
        settingsPanel.add(saveSettingsBtn);

        // --- 2. Center: Split Pane (Left: Request | Right: Report & Chat) ---
        JSplitPane mainSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT);
        mainSplit.setResizeWeight(0.4);

        // Left Side: Request Preview
        requestPreviewArea = new JTextArea();
        requestPreviewArea.setEditable(false);
        requestPreviewArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane reqScroll = new JScrollPane(requestPreviewArea);
        reqScroll.setBorder(new TitledBorder("Sanitized Context"));

        // Right Side: Vertical Split (Top: Report, Bottom: Chat)
        JSplitPane rightSplit = new JSplitPane(JSplitPane.VERTICAL_SPLIT);
        rightSplit.setResizeWeight(0.6); // Report gets 60% height

        // Top Right: HTML Report Area
        reportArea = new JEditorPane();
        reportArea.setContentType("text/html");
        reportArea.setEditable(false);
        HTMLEditorKit kit = new HTMLEditorKit();
        reportArea.setEditorKit(kit); // Better HTML rendering
        JScrollPane reportScroll = new JScrollPane(reportArea);
        reportScroll.setBorder(new TitledBorder("AI Analysis Report"));

        // Bottom Right: Chat Interface
        JPanel chatPanel = new JPanel(new BorderLayout());
        chatPanel.setBorder(new TitledBorder("Chat with AI"));

        chatArea = new JTextArea();
        chatArea.setEditable(false);
        chatArea.setLineWrap(true);
        chatArea.setWrapStyleWord(true);
        chatArea.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        JScrollPane chatScroll = new JScrollPane(chatArea);

        JPanel inputPanel = new JPanel(new BorderLayout());
        chatInput = new JTextField();
        sendChatButton = new JButton("Send");

        // Send on Enter key
        chatInput.addActionListener(e -> performChat());
        sendChatButton.addActionListener(e -> performChat());

        inputPanel.add(chatInput, BorderLayout.CENTER);
        inputPanel.add(sendChatButton, BorderLayout.EAST);

        chatPanel.add(chatScroll, BorderLayout.CENTER);
        chatPanel.add(inputPanel, BorderLayout.SOUTH);

        rightSplit.setTopComponent(reportScroll);
        rightSplit.setBottomComponent(chatPanel);

        mainSplit.setLeftComponent(reqScroll);
        mainSplit.setRightComponent(rightSplit);

        // --- 3. Bottom: Action Buttons ---
        JPanel actionPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));

        JButton btnAnalyze = new JButton("Analyze Full Context");
        btnAnalyze.setBackground(new Color(60, 120, 216));
        btnAnalyze.setForeground(Color.WHITE);
        btnAnalyze.addActionListener(e -> runInitialAnalysis(PROMPT_ANALYZE));

        JButton btnReport = new JButton("Draft Finding Report");
        btnReport.addActionListener(e -> runInitialAnalysis(PROMPT_REPORT));

        JButton btnClear = new JButton("Reset");
        btnClear.addActionListener(e -> {
            reportArea.setText("");
            requestPreviewArea.setText("");
            chatArea.setText("");
            chatHistory.setLength(0); // Clear history
            currentReqResp = null;
            currentReportText = "";
            fullContextString = "";
        });

        actionPanel.add(btnAnalyze);
        actionPanel.add(btnReport);
        actionPanel.add(btnClear);

        // Assembly
        add(settingsPanel, BorderLayout.NORTH);
        add(mainSplit, BorderLayout.CENTER);
        add(actionPanel, BorderLayout.SOUTH);

        setInitialWelcome();
    }
    
    private void saveSettings() {
        persistence.setString(KEY_API_URL, apiUrlField.getText().trim());
        persistence.setString(KEY_MODEL, modelNameField.getText().trim());
        JOptionPane.showMessageDialog(this, "Settings saved!");
    }

    private void setInitialWelcome() {
        reportArea.setText("<html><body style='font-family:sans-serif; padding:10px;'>" +
                "<h2>Bug Hunter's Copilot</h2>" +
                "<p>Ready to assist. Workflow:</p>" +
                "<ul>" +
                "<li>Right-click a request in Burp -> <b>Send to Copilot</b></li>" +
                "<li>Review the sanitized data on the left.</li>" +
                "<li>Click <b>Analyze</b> to get a logic breakdown.</li>" +
                "</ul></body></html>");
    }

    public void loadContext(HttpRequestResponse reqResp) {
        this.currentReqResp = reqResp;

        String rawReq = reqResp.request().toString();
        String cleanReq = sanitize(rawReq);
        String cleanResp = "[No Response Captured]";

        if (reqResp.hasResponse()) {
            String rawResp = reqResp.response().toString();
            if (rawResp.length() > 90000) {
                rawResp = rawResp.substring(0, 90000) + "\n...[TRUNCATED]...";
            }
            cleanResp = sanitize(rawResp);
        }

        this.fullContextString = "=== HTTP REQUEST ===\n" + cleanReq + "\n\n=== HTTP RESPONSE ===\n" + cleanResp;
        this.chatHistory.setLength(0); // New request -> New chat history

        SwingUtilities.invokeLater(() -> {
            requestPreviewArea.setText(fullContextString);
            reportArea.setText("<html><body><h3>Context Loaded.</h3><p>Ready to analyze.</p></body></html>");
            chatArea.setText("");
        });
    }

    private String sanitize(String raw) {
        String clean = raw;
        clean = clean.replaceAll("(?i)(Authorization:\\s+)(Bearer\\s+)?([\\w\\-\\._]+)", "$1$2[REDACTED_TOKEN]");
        clean = clean.replaceAll("(?i)(Cookie:\\s+)(.*)", "$1[REDACTED_COOKIES]");
        return clean;
    }

    // --- Logic 1: Initial Analysis (Populates Top Right) ---
    private void runInitialAnalysis(String systemPrompt) {
        if (fullContextString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No request loaded.");
            return;
        }

        reportArea.setText("<html><body><h3>Thinking...</h3></body></html>");

        CompletableFuture.runAsync(() -> {
            String fullPrompt = systemPrompt + "\n\nFULL TRAFFIC CONTEXT:\n" + fullContextString;
            String response = callOllamaAPI(fullPrompt);

            // Save this report as context for the chat!
            this.currentReportText = response;

            SwingUtilities.invokeLater(() -> {
                reportArea.setText("<html><body style='font-family:sans-serif; padding:10px;'>" + response + "</body></html>");
                reportArea.setCaretPosition(0);
                // Add system note to chat
                chatArea.append("--- Analysis Generated. You can now ask questions below ---\n\n");
            });
        });
    }

    // --- Logic 2: Chat (Populates Bottom Right) ---
    private void performChat() {
        String userQuestion = chatInput.getText().trim();
        if (userQuestion.isEmpty()) return;

        // Update UI immediately
        chatArea.append("You: " + userQuestion + "\n");
        chatInput.setText("");
        chatInput.setEnabled(false); // Disable input while thinking

        CompletableFuture.runAsync(() -> {
            // Build the Chat Prompt
            // We feed it: The Request + The AI's Own Report + Chat History + New Question
            String chatPrompt = "SYSTEM: You are a helpful security assistant. " +
                    "The user is asking about the HTTP request and the Analysis Report provided below.\n\n" +
                    "=== TRAFFIC DATA ===\n" + fullContextString + "\n\n" +
                    "=== YOUR ANALYSIS REPORT ===\n" + currentReportText + "\n\n" +
                    "=== CONVERSATION HISTORY ===\n" + chatHistory.toString() + "\n\n" +
                    "USER QUESTION: " + userQuestion;

            String aiResponse = callOllamaAPI(chatPrompt);

            // Update History
            chatHistory.append("User: ").append(userQuestion).append("\n");
            chatHistory.append("AI: ").append(aiResponse).append("\n");

            SwingUtilities.invokeLater(() -> {
                chatArea.append("AI: " + aiResponse + "\n\n");
                // Auto-scroll to bottom
                chatArea.setCaretPosition(chatArea.getDocument().getLength());
                chatInput.setEnabled(true);
                chatInput.requestFocus();
            });
        });
    }

    // --- Universal API Caller ---
    private String callOllamaAPI(String prompt) {
        try {
            String model = modelNameField.getText().trim();
            if (model.isEmpty()) model = DEFAULT_MODEL;
            
            String apiUrl = apiUrlField.getText().trim();
            if (apiUrl.isEmpty()) apiUrl = DEFAULT_API_URL;

            JsonObject jsonBody = new JsonObject();
            jsonBody.addProperty("model", model);
            jsonBody.addProperty("prompt", prompt);
            jsonBody.addProperty("stream", false);

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(apiUrl))
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(gson.toJson(jsonBody)))
                    .build();

            HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() == 200) {
                JsonObject responseJson = gson.fromJson(response.body(), JsonObject.class);
                if (responseJson.has("response")) {
                    return responseJson.get("response").getAsString();
                } else {
                    return "Error: Unexpected JSON format.";
                }
            } else {
                return "Error: API returned status " + response.statusCode();
            }
        } catch (Exception e) {
            return "Connection Error: " + e.getMessage() + "\nCheck if Ollama is running at " + apiUrlField.getText();
        }
    }
}
